version: '3'
services:
  fork:
    image: ghcr.io/foundry-rs/foundry:nightly-5c3b075f6e2adbba6089d15b383450930de283e7
    entrypoint: 'anvil -p 8545 --host 0.0.0.0 --chain-id 31337'
    ports:
      - '8545:8545'
