apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: validator
spec:
  serviceName: "validator"
  replicas: 1
  selector:
    matchLabels:
      app: validator
  template:
    metadata:
      labels:
        app: validator
    spec:
      initContainers:
        - name: configure-validator-env
          image: aztecprotocol/aztec:243df5dd6ae276b885f4d154e15e6fe47bfb10f5
          command:
            [
              "/bin/sh",
              "-c",
              "cp /scripts/configure-validator-env.sh /tmp/configure-validator-env.sh && chmod +x /tmp/configure-validator-env.sh && /tmp/configure-validator-env.sh",
            ]
          volumeMounts:
            - name: shared-volume
              mountPath: /shared
            - name: scripts
              mountPath: /scripts
          env:
            - name: ETHEREUM_HOST
              value: "http://ethereum.spartan:8545"
      containers:
        - name: aztec
          image: aztecprotocol/aztec:243df5dd6ae276b885f4d154e15e6fe47bfb10f5
          command:
            [
              "/bin/bash",
              "-c",
              "source /shared/contracts.env && env && node --no-warnings /usr/src/yarn-project/aztec/dest/bin/index.js start --node --archiver --sequencer --prover",
            ]
          volumeMounts:
            - name: shared-volume
              mountPath: /shared
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_DNS_NAME
              value: "$(POD_NAME).validator.$(POD_NAMESPACE).svc.cluster.local"
            - name: PORT
              value: "8080"
            - name: LOG_LEVEL
              value: "debug"
            - name: DEBUG
              value: "aztec:*"
            - name: ETHEREUM_HOST
              value: "http://ethereum.spartan:8545"
            - name: P2P_ENABLED
              value: "true"
            - name: P2P_TCP_ANNOUNCE_ADDR
              value: "$(POD_DNS_NAME):40400"
            - name: P2P_UDP_ANNOUNCE_ADDR
              value: "$(POD_DNS_NAME):40400"
            - name: P2P_TCP_LISTEN_ADDR
              value: 0.0.0.0:40400
            - name: P2P_UDP_LISTEN_ADDR
              value: 0.0.0.0:40400
            - name: BOOTSTRAP_NODES
              value: enr:-Jq4QCXaAMeJOV2x7KtRnlRRDsk-IkcDPrsaZlv6YjS-zQG_KYeL8sWIGDQhW5Q4Me52ZakUrHr1pGxYJ96kb0WtD8MGjWF6dGVjX25ldHdvcmsBgmlkgnY0gmlwhAr0AFKJc2VjcDI1NmsxoQJCgkvy-XI7OMRmPDJPt7kwvzl3cX34ixr0KcJvYHp0_4N0Y3CCndCDdWRwgp3Q
          ports:
            - containerPort: 8080
            - containerPort: 40400
      volumes:
        - name: shared-volume
          emptyDir: {}
        - name: scripts
          configMap:
            name: configure-validator-env
