apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: validator
spec:
  serviceName: "validator"
  replicas: 1
  selector:
    matchLabels:
      app: validator
  template:
    metadata:
      labels:
        app: validator
    spec:
      initContainers:
        - name: configure-validator-env
          image: aztecprotocol/aztec:803fd7e08dc236027fc5cd12996c88ee679a30a9
          command:
            [
              "/bin/sh",
              "-c",
              "cp /scripts/configure-validator-env.sh /tmp/configure-validator-env.sh && chmod +x /tmp/configure-validator-env.sh && /tmp/configure-validator-env.sh",
            ]
          volumeMounts:
            - name: shared-volume
              mountPath: /shared
            - name: scripts
              mountPath: /scripts
          env:
            - name: ETHEREUM_HOST
              value: "http://ethereum.spartan:8545"
      containers:
        - name: aztec
          image: aztecprotocol/aztec:803fd7e08dc236027fc5cd12996c88ee679a30a9
          command:
            [
              "/bin/bash",
              "-c",
              "source /shared/contracts.env && env && node --no-warnings /usr/src/yarn-project/aztec/dest/bin/index.js start --node --archiver --sequencer --prover",
            ]
          volumeMounts:
            - name: shared-volume
              mountPath: /shared
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_DNS_NAME
              value: "$(POD_NAME).validator.$(POD_NAMESPACE).svc.cluster.local"
            - name: PORT
              value: "8080"
            - name: LOG_LEVEL
              value: "debug"
            # - name: DEBUG
            #   value: "discv5:*,aztec:discv5_service:*,aztec:libp2p_service:*"
            - name: ETHEREUM_HOST
              value: "http://ethereum.spartan:8545"
            - name: P2P_ENABLED
              value: "true"
            - name: P2P_TCP_ANNOUNCE_ADDR
              value: "$(POD_DNS_NAME):40400"
            - name: P2P_UDP_ANNOUNCE_ADDR
              value: "$(POD_DNS_NAME):40400"
            - name: P2P_TCP_LISTEN_ADDR
              value: 0.0.0.0:40400
            - name: P2P_UDP_LISTEN_ADDR
              value: 0.0.0.0:40400
            - name: BOOTSTRAP_NODES
              value: enr:-KW4QH6goWfOR0V7KiH39jiK6QsDvJnNMRCeMqu3vuBuCVtBO0-oFaLpbM09mAs4oF4QDnra-VHqiMiTbwFCkk-0LQwGjWF6dGVjX25ldHdvcmsBgmlkgnY0g2lwNowLMTAuMjQ0LjAuNTOJc2VjcDI1NmsxoQJCgkvy-XI7OMRmPDJPt7kwvzl3cX34ixr0KcJvYHp0_4R0Y3A2gp3QhHVkcDaCndA
          ports:
            - containerPort: 8080
            - containerPort: 40400
      volumes:
        - name: shared-volume
          emptyDir: {}
        - name: scripts
          configMap:
            name: configure-validator-env
