name: 'Cache Successes'
branding:
  icon: 'server'
  color: 'orange'
inputs:
  success_key:
    description: "The key to remember successes based on."
    required: false
runs:
  using: 'node20'
  main: restore.js
  post: save.js
  post-if: success()