[package]
name = "proxy_contract"
type = "contract"
authors = [""]
compiler_version = ">=0.24.0"

[dependencies]
aztec = { path = "../../../aztec-nr/aztec" }
value_note = { path = "../../../aztec-nr/value-note" }