[package]
name = "proxy_contract"
type = "contract"
authors = [""]
compiler_version = ">=0.24.0"

[dependencies]
aztec = { path = "../../../aztec-nr/aztec" }
field_note = { path = "../../../aztec-nr/field-note" }