name: Run on Builder
description: "Target builder with actions"

inputs:
  run:
    required: true
  run_id:
    required: true
runs:
  # define an action, runs in OS of caller
  using: composite
  steps:
    # Assumes ensure-builder with a no-cache option has ran and SPOT_IP/SPOT_KEY are defined
    - name: Run On Spot
      env:
        # avoid double shell interpolation
        RUN_SCRIPT: export GITHUB_REF_NAME=${{ github.ref_name }} ; cd ~/run-${{ env.RUN_ID }} ; ${{ inputs.run }}
      shell: bash
      run: scripts/run_on_tester "$RUN_SCRIPT"
