apiVersion: v1
kind: Service
metadata:
  name: {{ include "spartan-network.fullname" . }}-ethereum
  labels:
    {{- include "spartan-network.labels" . | nindent 4 }}
spec:
  type: {{ .Values.ethereum.service.type }}
  selector:
    {{- include "spartan-network.selectorLabels" . | nindent 4 }}
    app: ethereum
  ports:
    - protocol: TCP
      port: {{ .Values.ethereum.service.port }}
      targetPort: {{ .Values.ethereum.service.targetPort }}
      {{- if and (eq .Values.ethereum.service.type "NodePort") .Values.ethereum.service.nodePort }}
      nodePort: {{ .Values.ethereum.service.nodePort }}
      {{- end }}