# This file uses YAML anchors and aliases to prevent repetition of blocks of config:
# https://support.atlassian.com/bitbucket-cloud/docs/yaml-anchors/
#
# Two primary anchors are checkout and setup_env, called as the first step of almost all jobs:
# - checkout: A custom checkout step to reduce the amount of data downloaded to improve speed.
# - setup_env: Sets up the common environment used by all build steps.
#
# Two CCI executors are used:
# - docker (small): Used only to launch external EC2 instances for big workloads. It's the cheapest option.
# - machine (large): Used for building in CCI itself. 4cpus, 15GB has the optimal power/cost ratio.
#
# The docker executor uses a custom image build in `build_image`. It's specifically streamlined for fast download
# with just enough tools to execute the build system, and launch EC2 instances etc.
#
# There are some `join` steps that are just no-ops. They are just used to produce cleaner graph rendering in CCI.

version: 2.1

setup: true # have a dynamic config step
orbs:
  continuation: circleci/continuation@1.0.0
  slack: circleci/slack@4.12.5

# This build step checks out the code from the repository. It has a hardcoded readonly key to allow the checkout.
# Initially it just fetches the repo metadata for the current commit hash to a depth of 50 commits.
# We need historical commit hashes to calculate diffs between previous and current commits.
# It then checks out the fetched head to actually download the data.
checkout: &checkout
  run:
    name: "Checkout code"
    command: |
      function retry() {
        # Retries up to 3 times with 10 second intervals
        for i in $(seq 1 3); do
          "$@" && return || sleep 10
        done
        echo "$@ failed after 3 attempts"
        exit 1
      }
      cd $HOME
      mkdir -p .ssh
      chmod 0700 .ssh
      retry ssh-keyscan -t rsa github.com >> .ssh/known_hosts

      # A read only key for cloning the repository.
      echo $GIT_CHECKOUT_KEY | base64 -d > .ssh/id_rsa

      chmod 0600 .ssh/id_rsa
      # IF YOU'RE CHANGING THIS, YOU ALSO WANT TO CHANGE: build-system/scripts/remote_runner
      # Shallow checkout this commit.
      mkdir -p project
      cd project
      git init
      git remote add origin $CIRCLE_REPOSITORY_URL

      # Only download metadata when fetching.
      retry git fetch --depth 1 --filter=blob:none origin $CIRCLE_SHA1
      retry git checkout FETCH_HEAD

# Called setup_env to setup a bunch of global variables used throughout the rest of the build process.
# It takes the required CCI environment variables as inputs, and gives them normalized names for the rest of
# the build process. This enables easy running of the build system external to CCI, as used for powerful EC2 builds.
setup_env: &setup_env
  run:
    name: "Setup environment"
    command: ./build-system/scripts/setup_env "$CIRCLE_SHA1" "$CIRCLE_TAG" "$CIRCLE_JOB" "$CIRCLE_REPOSITORY_URL" "$CIRCLE_BRANCH" "$CIRCLE_PULL_REQUEST"

defaults_e2e_test: &defaults_e2e_test
    docker:
      - image: aztecprotocol/alpine-build-image
    resource_class: small

jobs:
  # Noir
  noir-x86_64:
    docker:
      - image: aztecprotocol/alpine-build-image
    resource_class: small
    steps:
      - *checkout
      - *setup_env
      - run:
          name: "Build"
          command: cond_spot_run_build noir 32
          aztec_manifest_key: noir

  noir-arm64:
    docker:
      - image: aztecprotocol/alpine-build-image
    resource_class: small
    steps:
      - *checkout
      - *setup_env
      - run:
          name: "Build"
          command: cond_spot_run_build noir 32 arm64
          aztec_manifest_key: noir

  noir-ecr-manifest:
    machine:
      image: default
    resource_class: medium
    steps:
      - *checkout
      - *setup_env
      - run:
          name: "Create ECR manifest"
          command: create_ecr_manifest noir x86_64,arm64
          aztec_manifest_key: noir

  noir-tests:
    docker:
      - image: aztecprotocol/alpine-build-image
    resource_class: small
    steps:
      - *checkout
      - *setup_env
      - run:
          name: "Build"
          command: cond_spot_run_build noir-tests 32
          aztec_manifest_key: noir-tests

  noir-packages:
    docker:
      - image: aztecprotocol/alpine-build-image
    resource_class: small
    steps:
      - *checkout
      - *setup_env
      - run:
          name: "Build"
          command: cond_spot_run_build noir-packages 32
          aztec_manifest_key: noir-packages

  noir-packages-tests:
    docker:
      - image: aztecprotocol/alpine-build-image
    resource_class: small
    steps:
      - *checkout
      - *setup_env
      - run:
          name: "Build"
          command: cond_spot_run_build noir-packages-tests 32
          aztec_manifest_key: noir-packages-tests

  noir-compile-acir-tests:
    docker:
      - image: aztecprotocol/alpine-build-image
    resource_class: small
    steps:
      - *checkout
      - *setup_env
      - run:
          name: "Build"
          command: cond_spot_run_build noir-compile-acir-tests 32
          aztec_manifest_key: noir-compile-acir-tests

  avm-transpiler:
    docker:
      - image: aztecprotocol/alpine-build-image
    resource_class: small
    steps:
      - *checkout
      - *setup_env
      - run:
          name: "Build"
          command: cond_spot_run_build avm-transpiler 32
          aztec_manifest_key: avm-transpiler

  # Barretenberg
  barretenberg-wasm-linux-clang:
    docker:
      - image: aztecprotocol/alpine-build-image
    resource_class: small
    steps:
      - *checkout
      - *setup_env
      - run:
          name: "Build"
          command: cond_spot_run_build barretenberg-wasm-linux-clang 128
          aztec_manifest_key: barretenberg-wasm-linux-clang

  barretenberg-x86_64-linux-gcc:
    docker:
      - image: aztecprotocol/alpine-build-image
    resource_class: small
    steps:
      - *checkout
      - *setup_env
      - run:
          name: "Build"
          command: cond_spot_run_build barretenberg-x86_64-linux-gcc 128
          aztec_manifest_key: barretenberg-x86_64-linux-gcc

  barretenberg-x86_64-linux-clang:
    docker:
      - image: aztecprotocol/alpine-build-image
    resource_class: small
    steps:
      - *checkout
      - *setup_env
      - run:
          name: "Build"
          command: cond_spot_run_build barretenberg-x86_64-linux-clang 128
          aztec_manifest_key: barretenberg-x86_64-linux-clang

  barretenberg-x86_64-linux-clang-fuzzing:
    docker:
      - image: aztecprotocol/alpine-build-image
    resource_class: small
    steps:
      - *checkout
      - *setup_env
      - run:
          name: "Build"
          command: cond_spot_run_build barretenberg-x86_64-linux-clang-fuzzing 128
          aztec_manifest_key: barretenberg-x86_64-linux-clang-fuzzing

  barretenberg-x86_64-linux-clang-assert:
    docker:
      - image: aztecprotocol/alpine-build-image
    resource_class: small
    steps:
      - *checkout
      - *setup_env
      - run:
          name: "Build"
          command: cond_spot_run_build barretenberg-x86_64-linux-clang-assert 128
          aztec_manifest_key: barretenberg-x86_64-linux-clang-assert

  barretenberg-x86_64-linux-clang-sol:
    docker:
      - image: aztecprotocol/alpine-build-image
    resource_class: small
    steps:
      - *checkout
      - *setup_env
      - run:
          name: "Build"
          command: cond_spot_run_build barretenberg-x86_64-linux-clang-sol 32
          aztec_manifest_key: barretenberg-x86_64-linux-clang-sol

  barretenberg-docs:
    machine:
      image: default
    resource_class: large
    steps:
      - *checkout
      - *setup_env
      - run:
          name: "Build barretenberg docs"
          command: build barretenberg-docs
          aztec_manifest_key: barretenberg-docs
      - run:
          name: "Deploy barretenberg docs"
          command: |
            barretenberg/cpp/scripts/ci/upload_doxygen_to_s3.sh

  barretenberg-build:
    machine:
      image: default
    resource_class: small
    steps:
      - *checkout
      - *setup_env
      - run:
          name: "Build"
          command: cd barretenberg/cpp && earthly +build-ci

  yarn-project:
    machine:
      image: default
    resource_class: small
    steps:
      - *checkout
      - *setup_env
      - run:
          name: "Build"
          command: |
            git submodule init
            cd yarn-project && earthly +build

  barretenberg-benches:
    docker:
      - image: aztecprotocol/alpine-build-image
    resource_class: small
    steps:
      - *checkout
      - *setup_env
      - run:
          name: "Test"
          command: aws_run 16 "cd barretenberg/cpp && earthly_local +bench-ci"

# Repeatable config for defining the workflow below.
defaults: &defaults
  filters:
    tags:
      only: /^aztec-packages-v.*/
    # We would like to ignore release-please branches,
    # but doing so breaks github status checks:
    # the PR spins as it waits for the status check to complete,
    # which never happens because the branch is ignored.
    # Long term solution would require disabling the status checks on `master`
    # when the *source branch* on the PR release-please.
    # branches:
    #   ignore:
    #     - /^release-please--.*/
  context:
    - build
    - slack
  post-steps:
    - slack/notify:
        event: fail
        branch_pattern: "master"

# Workflows.
workflows:
  system:
    jobs:
      - barretenberg-build: *defaults
      - barretenberg-benches: *defaults
      - yarn-project: *defaults