images:
  test:
    image: aztecprotocol/spartan-test:8d93a281899690cb3d906abe9e7d434f4222c43e
    pullPolicy: IfNotPresent
  aztec:
    image: aztecprotocol/aztec:8d93a281899690cb3d906abe9e7d434f4222c43e
    pullPolicy: IfNotPresent
  curl:
    image: curlimages/curl:7.81.0
    pullPolicy: IfNotPresent
  foundry:
    image: ghcr.io/foundry-rs/foundry@sha256:29ba6e34379e79c342ec02d437beb7929c9e254261e8032b17e187be71a2609f
    pullPolicy: IfNotPresent

bootNode:
  replicas: 1
  service:
    p2pPort: 40400
    nodePort: 8080
  logLevel: 'debug'
  debug: 'discv5:*,aztec:*'
  p2p:
    enabled: 'true'
  resources: {}

validator:
  replicas: 1
  service:
    p2pPort: 40400
    nodePort: 8080
  logLevel: 'debug'
  debug: 'discv5:*,aztec:*'
  p2p:
    enabled: 'true'
  resources: {}

pxe:
  replicas: 1
  service:
    type: ClusterIP
    port: 8080
    targetPort: 8080
  resources: {}

ethereum:
  replicas: 1
  chainId: 31337
  forkUrl: ''
  forkBlockNumber: ''
  service:
    type: ClusterIP
    port: 8545
    targetPort: 8545
  readinessProbe:
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 3
  resources: {}
