[package]
name = "fee_enabled_schnorr_account_contract"
authors = [""]
compiler_version = ">=0.18.0"
type = "contract"

[dependencies]
aztec = { path = "../../../aztec-nr/aztec" }
authwit = { path = "../../../aztec-nr/authwit" }
schnorr_account_contract = { path = "../schnorr_account_contract" }
