# Reusable setup workflow for CI tasks
name: Setup Workflow
description: "Reusable setup steps"

inputs:
  concurrency_key:
    required: false
    description: "Concurrency key for locking jobs"

runs:
  # define an action, runs in OS of caller
  using: composite
  steps:
    - name: Cache Submodules
      id: cache-submodules
      uses: actions/cache@v4
      with:
        path: .git/modules
        key: submodules-${{ hashFiles('.gitmodules') }}

    - name: Checkout Submodules
      shell: bash
      run: |
        git config --global --add safe.directory '*'
        git submodule sync --recursive && git submodule update --init --recursive

    - name: Setup Earthly
      uses: earthly/actions-setup@v1
      with:
        # NOTE also update in ci/start-runner/src/userdata.ts
        version: "v0.8.10"

    - name: Setup Env
      shell: bash
      run: ./ci/setup_env.sh ${{ env.DOCKERHUB_PASSWORD }}
      env:
        PULL_REQUEST: "${{ github.event.pull_request.number }}"
        BRANCH: "${{ github.ref_name }}"

    # As detailed in https://github.com/ben-z/gh-action-mutex
    # things do not become 'pending' in github actions, and instead just cancel one another
    # so we can't use the native concurrency in GA. We use a simple file-lock since we're on the same machine.
    - name: Limit concurrency
      uses: gacts/run-and-post-run@v1
      if: ${{ inputs.concurrency_key }}
      with:
        run: |
          ci/runner-scripts/local_lock
        post: |
          ci/runner-scripts/local_unlock
          rm "/home/ubuntu/${{ inputs.concurrency_key }}.lock" || true
          echo "/home/ubuntu/${{ inputs.concurrency_key }}.lock removed."

    - name: Wait for runner completion
      shell: bash
      run: |
        for i in {1..60} ; do
          # HACK: detecting bare spot. TODO Find better solution
          [ ! -f ~/delay_shutdown.sh ] && ( ! [ -f ~/.user-data-started ] || [ -f ~/.user-data-finished ] ) && break
          [ -f ~/.setup-complete ] && ( ! [ -f ~/.user-data-started ] || [ -f ~/.user-data-finished ] ) && break
          sleep 1
        done
        if ! [ -f ~/.setup-complete ] && [ -f ~/.user-data-started ] ; then
          echo "Cache mount not seeming to be complete, exiting!"
          exit 1
        fi
