apiVersion: v1
kind: Service
metadata:
  name: {{ include "spartan-network.fullname" . }}-pxe
  labels:
    {{- include "spartan-network.labels" . | nindent 4 }}
spec:
  type: {{ .Values.pxe.service.type }}
  selector:
    {{- include "spartan-network.selectorLabels" . | nindent 4 }}
    app: pxe
  ports:
    - protocol: TCP
      port: {{ .Values.pxe.service.port }}
      targetPort: {{ .Values.pxe.service.targetPort }}
      {{- if and (eq .Values.pxe.service.type "NodePort") .Values.pxe.service.nodePort }}
      nodePort: {{ .Values.pxe.service.nodePort }}
      {{- end }}