[package]
name = "private_kernel_bin"
type = "bin"
compiler_version = "0.10.1"

[dependencies]
# private_kernel_init = { path = "../private-kernel-init" }
private_kernel_inner = { path = "../private-kernel-inner" }
private_kernel_ordering = { path = "../private-kernel-ordering" }
private_kernel_lib = { path = "../private-kernel-lib" }
