[package]
name = "ice_contract"
authors = [""]
compiler_version = ">=0.18.0"
type = "contract"

[dependencies]
aztec = { path = "../../../aztec-nr/aztec" }
ice_dependency = { path = "../ice_dependency" }
