apiVersion: apps/v1
kind: Deployment
metadata:
  name: ethereum
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ethereum
  template:
    metadata:
      labels:
        app: ethereum
    spec:
      containers:
        - name: ethereum
          image: ghcr.io/foundry-rs/foundry@sha256:29ba6e34379e79c342ec02d437beb7929c9e254261e8032b17e187be71a2609f
          command: ["/bin/sh", "-c"]
          args:
            - |
              ARGS="";
              [ -n "$FORK_URL" ] && ARGS="$ARGS --fork-url $FORK_URL";
              [ -n "$FORK_BLOCK_NUMBER" ] && ARGS="$ARGS --fork-block-number $FORK_BLOCK_NUMBER";
              echo anvil -p $ANVIL_PORT --host 0.0.0.0 --chain-id 31337 $ARGS;
              anvil -p $ANVIL_PORT --host 0.0.0.0 --chain-id 31337 $ARGS;
          ports:
            - containerPort: 8545
              name: anvil
          env:
            - name: FORK_URL
              valueFrom:
                configMapKeyRef:
                  name: ethereum-config
                  key: fork-url
            - name: FORK_BLOCK_NUMBER
              valueFrom:
                configMapKeyRef:
                  name: ethereum-config
                  key: fork-block-number
            - name: ANVIL_PORT
              valueFrom:
                configMapKeyRef:
                  name: ethereum-config
                  key: anvil-port
