# Publishes the remote cache https://docs.earthly.dev/docs/caching/caching-via-registry#inline-cache
# We do this on a dedicated runner
name: Publish Cache
on:
  workflow_dispatch: {}
  push:
    branches: [ad/inline-caching] #[master]
env:
  USERNAME: master-cache-x86
jobs:
  publish:
    runs-on: ubuntu-latest
    concurrency:
      # write this with a queue (note rapid fire jobs may have some cancelled)
      group: publish-master-cache
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Publish Barretenberg Base Images
        working-directory: ./.github/ensure-builder
        # give lots of leeway for full builds + slow push
        timeout-minutes: 60
        run: |
          git submodule update --init --recursive
          scripts/earthly-ci --save-inline-cache --push +build
