# Runs the entire new CI mode.
name: Run CI with Earthly
on:
  push:
    branches:
      - master
  pull_request: {}
  workflow_dispatch: {}
jobs:
  ci-x86:
    runs-on: ubuntu-latest
    # TODO enable after stress tests
    # concurrency:
    #   group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}-x86
    #   cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          submodules: recursive
      - name: setup
        run: |
          mkdir -p ~/.ssh
          echo DOCKER_HOST=ssh://build-instance-x86.aztecprotocol.com >> $GITHUB_ENV
          echo ${{ secrets.DOCKERHUB_PASSWORD}} | docker login -u aztecprotocolci --password-stdin
          echo ${{ secrets.BUILD_INSTANCE_SSH_KEY }} | base64 -d > ~/.ssh/build_instance_key
          chmod 600 ~/.ssh/build_instance_key
          cat > ~/.ssh/config <<EOF
          IdentityFile ~/.ssh/build_instance_key
          StrictHostKeyChecking no
          User ubuntu
          EOF
      # - name: ensure-base-images
      #   run: |
      #     scripts/earthly --push ./foundry/+build
      #      scripts/earthly --push ./barretenberg/cpp/+build-wasi-sdkV
      - name: ci
        run: scripts/earthly --exec-stats +build-ci-small

  ci-arm:
    runs-on: ubuntu-latest
    # TODO enable after stress tests
    # concurrency:
    #   group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}-arm
    #   cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          submodules: recursive
      - name: setup
        run: |
          mkdir -p ~/.ssh
          echo DOCKER_HOST=ssh://build-instance-arm.aztecprotocol.com >> $GITHUB_ENV
          echo ${{ secrets.DOCKERHUB_PASSWORD}} | docker login -u aztecprotocolci --password-stdin
          echo ${{ secrets.BUILD_INSTANCE_SSH_KEY }} | base64 -d > ~/.ssh/build_instance_key
          chmod 600 ~/.ssh/build_instance_key
          cat > ~/.ssh/config <<EOF
          IdentityFile ~/.ssh/build_instance_key
          StrictHostKeyChecking no
          User ubuntu
          EOF
      - name: ensure-base-images
        run: |
          scripts/earthly --push ./foundry/+build
          # scripts/earthly --push ./barretenberg/cpp/+build-wasi-sdk
      - name: ci
        run: scripts/earthly --exec-stats +build-ci-small
