# Runs the entire new CI mode.
name: Run CI with Earthly
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  ci-x86:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}-x86
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
      - name: setup
        run: |
          mkdir -p ~/.ssh
          echo ${{ secrets.BUILD_INSTANCE_SSH_KEY }} | base64 -d > ~/.ssh/build_instance_key
          echo DOCKER_HOST=ssh://build-instance-x86.aztecprotocol.com >> $GITHUB_EN
          chmod 600 ~/.ssh/build_instance_key
          cat > ~/.ssh/config <<EOF
          IdentityFile ~/.ssh/build_instance_key
          StrictHostKeyChecking no
          User ubuntu
          EOF
      # - name: ensure-base-images
      #   run: |
      #     scripts/earthly --push foundry/+build
      #      scripts/earthly --push barretenberg/cpp/+build-wasi-sdkV
      - name: ci
        run: scripts/earthly --ci +build-ci-small

  ci-arm:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}-arm
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
      - name: setup
        run: |
          mkdir -p ~/.ssh
          echo DOCKER_HOST=ssh://build-instance-arm.aztecprotocol.com >> $GITHUB_ENV
          echo ${{ secrets.BUILD_INSTANCE_SSH_KEY }} | base64 -d > ~/.ssh/build_instance_key
          chmod 600 ~/.ssh/build_instance_key
          cat > ~/.ssh/config <<EOF
          IdentityFile ~/.ssh/build_instance_key
          StrictHostKeyChecking no
          User ubuntu
          EOF
      - name: ensure-base-images
        run: |
          scripts/earthly --push foundry/+build
          # scripts/earthly --push barretenberg/cpp/+build-wasi-sdk
      - name: ci
        run: scripts/earthly --ci +build-ci-small
