name: Run CI with Earthly
on:
  push:
    branches:
      - master
  pull_request: {}
  workflow_dispatch: {}

jobs:
  e2e:
    runs-on: ubuntu-latest
    strategy:
      { matrix: { environment: [x86, arm], test: [e2e-escrow-contract] } }
    # cancel if reran on same PR if exists, otherwise if on same commit
    concurrency:
      group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}-${{ matrix.environment }}
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          submodules: recursive

      - name: Setup
        working-directory: ./scripts
        run: ./setup_env.sh ${{ matrix.environment }} ${{ secrets.DOCKERHUB_PASSWORD }} ${{ secrets.BUILD_INSTANCE_SSH_KEY }}

      - name: Test
        working_directory: ./yarn-project/end-to-end
        run: earthly +${{ matrix.test }}

  bb-native-tests:
    runs-on: ubuntu-latest
    # run for both x86_64 and arm64
    strategy: { matrix: { environment: [x86, arm] } }
    # cancel if reran on same PR if exists, otherwise if on same commit
    concurrency:
      group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}-${{ matrix.environment }}
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          submodules: recursive

      - name: Setup
        working-directory: ./scripts
        run: ./setup_env.sh ${{ matrix.environment }} ${{ secrets.DOCKERHUB_PASSWORD }} ${{ secrets.BUILD_INSTANCE_SSH_KEY }}

      - name: Build and test
        working-directory: ./barretenberg/cpp
        run: earthly +test
