# Runs the entire new CI mode.
name: Run CI with Earthly
on:
  schedule:
    # Run the workflow every night at 2:00 AM UTC.
    - cron: "0 2 * * *"

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'true'
          fetch-depth: 0
      - name: ci
        run: scripts/earthly
