# Runs the entire new CI mode.
name: Run CI with Earthly
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  ci:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'true'
          fetch-depth: 0
      - name: ci
        run: scripts/earthly
