name: Publish public artifacts
on:
  workflow_dispatch:
    inputs:
      tag:
        description: The tag to build from.
        required: true

concurrency:
  # This only runs on master
  group: ci-${{ github.run_id || github.ref_name }}
  cancel-in-progress: true

jobs:
  setup_x86:
    uses: ./.github/workflows/setup-runner.yml
    with:
      username: master
      runner_type: builder-x86
    secrets: inherit

  setup_arm:
    uses: ./.github/workflows/setup-runner.yml
    with:
      username: master
      runner_type: builder-arm
    secrets: inherit

  build:
    strategy:
      matrix:
        include:
          - arch: x86_64
            runner-label: master-x86
          - arch: arm64
            runner-label: master-arm
    runs-on: ${{ matrix.runner-label }}
    steps:
      - uses: actions/checkout@v4
        with: { ref: "${{ env.GIT_COMMIT }}" }
      - uses: ./.github/ci-setup-action
        with:
          dockerhub_password: "${{ secrets.DOCKERHUB_PASSWORD }}"
          concurrency_key: build-release-artifacts-${{ github.actor }}-${{ matrix.arch }}
      - name: "Build images"
        timeout-minutes: 40
        # Run the build steps for each image with version and arch, push to dockerhub
        run: |
          earthly-ci --no-output --push ./yarn-project+export-aztec-arch --DIST_TAG=${{ inputs.tag }} --ARCH=${{ matrix.arch }}
          earthly-ci --no-output --push ./yarn-project+export-aztec-builder --DIST_TAG=${{ inputs.tag }} --ARCH=${{ matrix.arch }}
          earthly-ci --no-output --push ./noir+export-noir --DIST_TAG=${{ inputs.tag }} --ARCH=${{ matrix.arch }}

  publish-dockerhub:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image_name: [aztec, aztec-builder, noir]
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - uses: ./.github/ci-setup-action
        with:
          dockerhub_password: "${{ secrets.DOCKERHUB_PASSWORD }}"
          concurrency_key: publish-public-artifacts-${{ github.actor }}-x86

      - name: Publish versioned manifests to Dockerhub
        uses: ./github/ensure-builder
        with:
          run: |
            docker manifest create aztecprotocol/${{ matrix.image_name }}:${{ inputs.tag }} \
              --amend aztecprotocol/${{ matrix.image_name }}:${{ inputs.tag }}-x86_64 \
              --amend aztecprotocol/${{ matrix.image_name }}:${{ inputs.tag }}-arm64
            docker manifest push --purge aztecprotocol/${{ matrix.image_name }}:${{ inputs.tag }}

      - name: Publish latest manifests to Dockerhub
        uses: ./github/ensure-builder
        with:
          run: |
            docker pull aztecprotocol/${{ matrix.image_name }}:${{ inputs.tag }}
            docker tag aztecprotocol/${{ matrix.image_name }}:${{ inputs.tag }} aztecprotocol/${{ matrix.image_name }}:latest
            docker push aztecprotocol/${{ matrix.image_name }}:latest

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - uses: ./.github/ci-setup-action
        with:
          NPM_TOKEN: "${{ secrets.NPM_TOKEN }}"
          concurrency_key: publish-public-artifacts-${{ github.actor }}-x86

      - name: Publish to NPM
        uses: ./github/ensure-builder
        with:
          working-directory: yarn-project
          run: |
            earthly-ci --no-output --secret NPM_TOKEN=${{ secrets.NPM_TOKEN }} --build-arg VERSION=${{ inputs.tag }} --build-arg DIST_TAG=latest +publish-npm
