# Useful if the spot runners are in a bad state
name: Start/Stop Personal Spot
on:
  workflow_dispatch:
    inputs:
      username:
        description: 'Defaults to GitHub Actor'
        required: false
      action:
        description: 'Can also be stop or restart, defaults to start'
        required: false
        default: 'start'
jobs:
  start-build:
    uses: ./.github/workflows/setup-runner.yml
    with:
      runner_label: ${{ inputs.username || github.actor }}-x86
      runner_type: builder-x86
    secrets: inherit

  start-bench:
    uses: ./.github/workflows/setup-runner.yml
    with:
      runner_label: ${{ inputs.username || github.actor }}-bench-x86
      runner_type: bb-bench-x86
    secrets: inherit